### ISSUE TITLE
CMakeLists.txt modification needed to install pillow-jpls in Ubuntu container running on Apple M1 device

### ISSUE THREAD

**Issue by jackpaparian** [planetmarshall/pillow-jpls#12]
I'm currently running an `ubuntu:impish-20220404` container on an Apple M1 device.

`pip install pillow-jpls` fails with the error: `Could NOT find Python (missing: Interpreter Development.Module)`

I was able to compile `pillow-jpls` after modifying the [culprit line in CMakeLists.txt](https://github.com/planetmarshall/pillow-jpls/blob/main/CMakeLists.txt#L9) from `find_package(Python REQUIRED COMPONENTS Interpreter Development.Module)` to `find_package(Python REQUIRED COMPONENTS Interpreter Development)`. I locally built `pillow-jpls` with the following commands:
```
pip install pep517
python -m pep517.build --binary .
```

Would it be possible to update [this line in CMakeLists.txt](https://github.com/planetmarshall/pillow-jpls/blob/main/CMakeLists.txt#L9) and push a new release to PyPI? Thanks!

**Comment by jackpaparian** [comment]
Is there anything I could do to help with this change?

**Comment by planetmarshall** [comment]
> Is there anything I could do to help with this change?

Apologies - I lost track of this. Change building now - in future if you know the change you want to make, the easiest way is just to fork the repository and submit a pull request.

Thanks!

**Comment by planetmarshall** [comment]
There's currently an issue with the upstream conan package for pybind, I'll need some time to look into this. Maybe check back in a couple of days :)

**Comment by jackpaparian** [comment]
Thank you! I've confirmed that I can successfully build `pillow-jpls` from the latest commit https://github.com/planetmarshall/pillow-jpls/commit/833a3844fdc7ac4263668a40b60840d663d24865.

Are you planning to push [v1.2.0](https://github.com/planetmarshall/pillow-jpls/releases/tag/v1.2.0) to PyPI?

**Comment by planetmarshall** [comment]
> Thank you! I've confirmed that I can successfully build `pillow-jpls` from the latest commit [833a384](https://github.com/planetmarshall/pillow-jpls/commit/833a3844fdc7ac4263668a40b60840d663d24865).
> 
> Are you planning to push [v1.2.0](https://github.com/planetmarshall/pillow-jpls/releases/tag/v1.2.0) to PyPI?

Hi @jackpaparian - version 1.2.0 should now be on PyPi. Glad it's working for you.
